

export const rows = [
  {
    id: 1,
    Name: "Snow",
    Email: "Jon@gmail.com",
    age: 35,
    phone: 1234567890,
    access: "admin",
  },
  {
    id: 2,
    Name: "Lannister",
    Email: "lannister@gmail.com",
    age: 42,
    phone: 1234567890,
    access: "manager",
  },
  {
    id: 3,
    Name: "Lannister",
    Email: "jdj@gmail.com",
    age: 45,
    phone: 1234567890,
    access: "user",
  },
  {
    id: 4,
    Name: "Stark",
    Email: "stark@gmail.com",
    age: 16,
    phone: 1234567890,
    access: "user",
  },
  {
    id: 5,
    Name: "Targaryen",
    Email: "targ@gmail.com",
    age: 22,
    phone: 1234567890,
    access: "admin",
  },
  {
    id: 6,
    Name: "Melisandre",
    Email: "khdh@gmail.com",
    age: 15,
    phone: 1234567890,
    access: "user",
  },
  {
    id: 7,
    Name: "Clifford",
    Email: "iehei]@hmail.com",
    age: 44,
    phone: 1234567890,
    access: "user",
  },
];
